POST http://localhost:4000/auth/users/register
Content-Type: application/json

{
    "username": "regular_user",
    "email": "user@example.com",
    "password" : "test"
}

###
POST http://localhost:4000/auth/users/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password" : "test"
}

###
GET http://localhost:4000/auth/users/
